### ISSUE TITLE
TypeError: Services.appinfo is undefined

### ISSUE THREAD

**Issue by rainemak** [sailfishos/sailfish-browser#1039]
There are several undefined Services.appinfo errors printed when starting esr91 browser engine.

JavaScript error: resource://gre/modules/LoginRecipes.jsm, line 56: TypeError: Services.appinfo is undefined
JavaScript error: file:///usr/lib64/mozembedlite/components/UserAgentOverrideHelper.js, line 110: TypeError: Services.appinfo is undefined
JavaScript error: resource://gre/modules/EnterprisePoliciesParent.jsm, line 500: TypeError: Services.appinfo is undefined
JavaScript error: resource://gre/modules/URLQueryStrippingListService.jsm, line 42: TypeError: Services.appinfo is undefined
JavaScript error: resource://gre/modules/Region.jsm, line 119: TypeError: Services.appinfo is undefined

Once Services.jsm returns appinfo correctly errors should be gone as both nsIXULAppInfo & nsIPlatformInfo look more or less the same they used to.

**Comment by llewelld** [comment]
This should be fixed by the following commit added to the sailfishos-esr91 branch:

https://github.com/llewelld/gecko-dev/commit/81f6912dfb7e6c5e23fb6c4d606ff02d54da7a55
