### ISSUE TITLE
Fix JavaScript errors from EmbedLiteChromeManager.js

### ISSUE THREAD

**Issue by rainemak** [sailfishos/sailfish-browser#1041]
Fix JavaScript errors from EmbedLiteChromeManager.js.

JavaScript error: file:///usr/lib64/mozembedlite/components/EmbedLiteChromeManager.js, line 213: NS_ERROR_FILE_NOT_FOUND:

**Comment by llewelld** [comment]
Upstream changes mean the `AboutCertViewerHandler` service is now an actor-based RPM comprised of `AboutCertViewerChild.jsm` and `AboutCertViewerParent.jsm` to replace the previous `AboutCertViewerHandler.jsm`.

As a result of this it apparently doesn't require either `init()` or `uninit()` to be called (they've both been removed). See [Bug 1646197](https://bugzilla.mozilla.org/show_bug.cgi?id=1646197) and the related changeset [D80017](https://phabricator.services.mozilla.com/D80017).

I couldn't see anywhere else in the EmbedLite code where the service is used, so hopefully any other changes needed will already be part of the upstream gecko-dev changes.

As a result I've reverted embedlite-components commit [b1510a7a](https://github.com/llewelld/embedlite-components/commit/b1510a7a5771906e44b4247bd75271c1bb5c54f6) which looks to be no longer necessary.

See commit [b3a105be](https://github.com/llewelld/embedlite-components/commit/b3a105befe7c5743c9e3b82887f4f69494cceea2).
