### ISSUE TITLE
Wikipedia not redirecting to mobile

### ISSUE THREAD

**Issue by attah** [sailfishos/sailfish-browser#1069]
Presumably it needs a UA tweak.
`Mozilla/5.0 (Android 8.1.0; Mobile; rv:78.0) Gecko/78.0 Firefox/78.0` works.

**Comment by rainemak** [comment]
Labeled this to esr91. Yes, if do an override it should be 91.0 based.

**Comment by rainemak** [comment]
Fixed here https://github.com/sailfishos/gecko-dev/pull/162/commits/46b42fdb72f1b9c94293bd77a1af789f03858ae2#diff-32f186c0ac568a4e9f672fccb51a5ac9201984e5efe08b94944b7dee5f4b6627
