### ISSUE TITLE
"Find in page" feature

### ISSUE THREAD

**Issue by FireyFly** [sailfishos/sailfish-browser#107]
This is a feature suggestion for a find-in-page feature, searching for a particular string in the body of a page. This feature is a staple in all modern web browsers, both for mobile and desktop devices, and seems like a crucial feature for the Sailfish browser.

* See also [Browser: Find in page](https://together.jolla.com/question/7132/browser-find-in-page/) on Together.

**Comment by anandrkris** [comment]
@rainemak - Can be closed, i suppose. Available i opt-in release in https://together.jolla.com/question/82037/release-notes-upgrade-112-yliaavanlampi-early-access/

**Comment by rainemak** [comment]
Yeap, thanks.
