### ISSUE TITLE
Set a new default override UA

### ISSUE THREAD

**Issue by attah** [sailfishos/sailfish-browser#1070]
Unless i messed something up, the default-ish UA in the overrides (the one for most sites) has 78 in it - and also Android 8.
Apparently we do need t lie to some websites, but shouldn't it at least say 91?

**Comment by attah** [comment]
Maybe something like `Mozilla/5.0 (Android 12; Mobile; rv:91.0) Gecko/91.0 Firefox/91.0`?
Supposedly it has been seen in the wild: https://myip.ms/view/comp_browseragents/2808495/Mozilla_5_0_Android_12_Mobile_rv_91_0_Gecko_91_0_Firefox_91_0.html

**Comment by rainemak** [comment]
Labeled this to esr91. Yes, if do an override it should be 91.0 based.

**Comment by rainemak** [comment]
It should be automatic given that all patches are applied properly.

https://github.com/sailfishos/gecko-dev/commit/51d6136d5f5aaa2d9b09af63b9ad6d3ff514e654

We changed to use OS agnostic user-agent back in 2020 by usign -DMOZ_UA_OS_AGNOSTIC=1  
https://github.com/sailfishos/gecko-dev/commit/17df02bdd4a65f4c90a4426b9190d020f6c3f3b5

On Sailfish OS gecko repository you can run something like:
> git log --author="Raine" --grep="user"

**Comment by attah** [comment]
Excellent! Then we probably just found a missing patch then.
Or wait... i'm confused - i'm talking about *overrides* here - i.e. what's in ua-update.json - which can be wildly different - so does this still apply?

**Comment by attah** [comment]
Definitely missing at least one of those patches.
My UA reports as `Mozilla/5.0 (X11; Linux aarch64; rv:91.0) Gecko/20100101 Firefox/91`
So with that sorted, this other issue may be redundant: https://github.com/sailfishos/sailfish-browser/issues/1069

**Comment by rainemak** [comment]
@attah that's correct analysis. It's now-a-days 0068-sailfishos-gecko-Start-using-user-agent-builder.-JB-.patch that we're lacking.

**Comment by rainemak** [comment]
Fixed here https://github.com/sailfishos/gecko-dev/pull/162/commits/46b42fdb72f1b9c94293bd77a1af789f03858ae2#diff-32f186c0ac568a4e9f672fccb51a5ac9201984e5efe08b94944b7dee5f4b6627
