### ISSUE TITLE
All webpages appear scaled down

### ISSUE THREAD

**Issue by affenull2345** [sailfishos/sailfish-browser#1072]
Sailfish OS 4.6.0.13, custom Samsung Galaxy A40 port

After upgrading to ESR 91, text (and everything else) on webpages appears very small, probably because the DPI scale is not being determined correctly. Setting the `layout.css.devPixelsPerPx` preference manually to the value 3.0 makes web pages appear normally again. This was not necessary for ESR 78.

This issue only occurs in the Browser application. E-mails and other web views are scaled correctly.

**Comment by vige** [comment]
After the latest packages with the user-agent fixes this issue becomes even worse, i.e. even sites which worked fine with the old packages (https://ilmatieteenlaitos.fi/, https://forum.sailfishos.org/) have too small text. The `devPixelsPerPx` workaround works though, thanks @affenull2345 !

**Comment by rainemak** [comment]
devPixelsPerPx works now-a-days with latest builds from sailfish-esr91 branches. I'm not sure about pre-build packages.

There's a follow-up task https://github.com/sailfishos/sailfish-browser/issues/1085 which imo would be even better than 3.0 devPixelsPerPx
