### ISSUE TITLE
VR Radalla doesn't load

### ISSUE THREAD

**Issue by direc85** [sailfishos/sailfish-browser#1076]
Finnish railroad informational page https://www.vr.fi/radalla/poikkeustilanteet doesn't load the list of issues, it just shows the loader which keeps animating.

The only thing in console is this:

`JavaScript error: https://www.vr.fi/_next/static/chunks/main-3c5d4165c5736cef.js, line 1: TypeError: e is undefined`

The file is minified, so it carries little information.

The same applies to https://www.vr.fi/radalla as well; same error, and none of the controls work (search field and the two buttons).

**Comment by tuplasuhveli** [comment]
I wasn't able to reproduce this one on Xperia 10 V.

Here's the view of a successful search on https://www.vr.fi/radalla :

![screenshot2](https://github.com/user-attachments/assets/7c62a215-a1a5-4aa9-aeab-98f44f744766)

Here's the view on https://www.vr.fi/radalla/poikkeustilanteet :

![screenshot](https://github.com/user-attachments/assets/3f5a9950-2d05-4cec-bc38-d107d0935ce4)

**Comment by rainemak** [comment]
@direc85 did you see this issue with esr92 or esr78?

Esr92 seems to work fine, no errors.
With esr78, I do not see reported error either but see "Käytät vanhentunutta selainta" => "You're using outdated browser".

**Comment by direc85** [comment]
I can't reproduce this any more. The addresses work fine with ESR91 now. The JS error is gone too.

With ESR78, they are broken: `/radalla` shows generic-looking UI elements that can't be interacted with, and `/radalla/poikkeustilanteet` only shows a tiny squashed VR loading animation, which never finishes.

Either VR fixed the bug right after I reported, or it was e.g. cache issue on my phone. I think this can be closed then?

**Comment by rainemak** [comment]
Let's close this.
