### ISSUE TITLE
[Site Issue] Search field loses focus/cannot input text [valintatalo.fi]

### ISSUE THREAD

**Issue by gitarra** [sailfishos/sailfish-browser#111]
Its not possible to use the highlighted search field on this page:

http://www.valintatalo.fi/fi/etusivu

When you tap the field the keyboard shows up, but then quickly disappears with the search field losing focus. Works on Webcat browser by refocusing with tapping the field twice.

![20140423092156](https://cloud.githubusercontent.com/assets/4739888/2774160/96670fd8-cab0-11e3-9f19-6419c7c35ccb.png)

**Comment by rainemak** [comment]
I don't not recall whether this was failing completely with Android FF. As "Postinumero tai -toimipaikka" field can be focused and input given, closing this as works for me.
