### ISSUE TITLE
JavaScript-heavy (asm.js) WebGL page crashes browser

### ISSUE THREAD

**Issue by thp** [sailfishos/sailfish-browser#124]
Steps to reproduce:

* Open http://thp.io/2014/petals/play/ in the browser
* Wait for the page to load

Expected result:

* Page loads and works, content is rendered via WebGL and has acceptable performance

Actual result:

* Browser locks up, then crashes

Other comments:

* The page works on Nexus 4 in Android (tested using Chrome 34 and Firefox 29)
* The page doesn't work on Firefox 29 running in Alien on Jolla (also crashes)
* The same code, running natively, works on SFOS on Jolla, so all the GL features it uses (FBOs with depth buffer, ...) should be supported by the GL driver

**Comment by siteshwar** [comment]
These are top frames of backtrace of the crash :

```
(gdb) bt
#0  0xb07fc3d4 in nsXPCWrappedJS::AddRef (this=0xa69be8c0)
    at /usr/src/debug/xulrunner-qt5-38.0.5.3+nemo_embedlite_38.20151109122853.9214377/js/xpconnect/src/XPCWrappedJS.cpp:228

#1  0xb05a61ce in nsXPTCStubBase::QueryInterface (this=0xa6999b70, aIID=..., aInstancePtr=0xa817c544)
    at /usr/src/debug/xulrunner-qt5-38.0.5.3+nemo_embedlite_38.20151109122853.9214377/xpcom/reflect/xptcall/xptcall.cpp:20

#2  0xb059dfea in nsComponentManagerImpl::GetServiceByContractID (this=0xabec4080, aContractID=0xb1866a18 "@mozilla.org/xre/app-info;1", aIID=..., aResult=0xa817c544)
    at /usr/src/debug/xulrunner-qt5-38.0.5.3+nemo_embedlite_38.20151109122853.9214377/xpcom/components/nsComponentManager.cpp:1544

#3  0xb05ac8d2 in nsGetServiceByContractID::operator() (this=this@entry=0xa817c53c, aIID=..., aInstancePtr=aInstancePtr@entry=0xa817c544)
    at /usr/src/debug/xulrunner-qt5-38.0.5.3+nemo_embedlite_38.20151109122853.9214377/xpcom/glue/nsComponentManagerUtils.cpp:280

#4  0xb05ac8ee in nsCOMPtr_base::assign_from_gs_contractid (this=0xa817c550, aGS=..., aIID=...)
    at /usr/src/debug/xulrunner-qt5-38.0.5.3+nemo_embedlite_38.20151109122853.9214377/xpcom/glue/nsCOMPtr.cpp:103

#5  0xb0dd19ac in nsCOMPtr (aGS=..., this=0xa817c550) at ../../dist/include/nsCOMPtr.h:514


#6  mozilla::dom::asmjscache::GetBuildId (aBuildID=0xa817c5e8)
    at /usr/src/debug/xulrunner-qt5-38.0.5.3+nemo_embedlite_38.20151109122853.9214377/dom/asmjscache/AsmJSCache.cpp:1727


#7  0xb1545476 in extractCurrentState (cx=0x9db9c280, this=0xa817c5e0)
    at /usr/src/debug/xulrunner-qt5-38.0.5.3+nemo_embedlite_38.20151109122853.9214377/js/src/asmjs/AsmJSModule.cpp:1880
```

I tried to see how this webpage works works with Desktop firefox and found that firefox uses a [different class](https://git.merproject.org/mer-core/gecko-dev/blob/b319d9fee054430ef39d5349fc49464c2a1559c9/toolkit/xre/nsAppRunner.cpp#L617) to call QueryInterface() method in [nsComponentManagerImpl::GetServiceByContractID](https://git.merproject.org/mer-core/gecko-dev/blob/b319d9fee054430ef39d5349fc49464c2a1559c9/xpcom/components/nsComponentManager.cpp#L1543). While Sailfish browser directly calls method in [nsXPTCStubBase::QueryInterface()](https://git.merproject.org/mer-core/gecko-dev/blob/b319d9fee054430ef39d5349fc49464c2a1559c9/xpcom/reflect/xptcall/xptcall.cpp#L16) off main thread which causes a crash in [AddRef](https://git.merproject.org/mer-core/gecko-dev/blob/b319d9fee054430ef39d5349fc49464c2a1559c9/xpcom/reflect/xptcall/xptcall.cpp#L20).

**Comment by rainemak** [comment]
Closing as this has been fixed already some time back. Asmjs will be enabled again on upgrade-2.0.4.
