### ISSUE TITLE
Use Button instead of MenuItem in BrowserContextMenu

### ISSUE THREAD

**Issue by dicksonleong** [sailfishos/sailfish-browser#15]
Using MenuItem seems inappropriate in BrowserContextMenu since it is not a good sign that those items are clickable and lack of (noticeable) visual feedback when those items are pressed. Buttons will be a better choice. Using buttons instead of MenuItem can also remove some confusing codes like `highlightItem()` and `setHighlightItem()` functions.

The guideline in [here](https://sailfishos.org/sailfish-silica/sailfish-application-pitfalls.html#incorrect-label-coloring) also state that `Theme.highlightColor` should be use for label that is non-interactive (which is the default color of MenuItem).

Just my suggestion, let me know what you think :)

Comparsion of MenuItems and Buttons:
![screenshot from 2014-02-16 00 57 57 resized](https://f.cloud.github.com/assets/2051511/2178332/188fc972-9664-11e3-9ceb-744508927021.png)
![screenshot from 2014-02-16 00 55 36 resized](https://f.cloud.github.com/assets/2051511/2178333/1c9fd96c-9664-11e3-9ec8-71cc427df1e1.png)

**Comment by rainemak** [comment]
Buttons are not really Sailfish style in this kind of cases - this is clearly menu item case. Closing.
