### ISSUE TITLE
Delete incorrect instance from list of history suggestions

### ISSUE THREAD

**Issue by anandrkris** [sailfishos/sailfish-browser#253]
If i have typed an incorrect URL previously, say, _googel.com_, currently there is no way to stop it from being suggested. And as it happens, i keep clicking the wrong suggestion. :wink: 

Can we have the option to delete such **individual entries**? Perhaps, by having an option called Delete on holding the entry.

**Comment by anandrkris** [comment]
https://together.jolla.com/question/83678/feature-request-options-when-clicking-on-a-url-in-browser-history/ Saw a TJC request for this today - Making a reference here...

**Comment by rainemak** [comment]
@anandrkris : The context menu option for deleting history entries is available in 2.0.5.6 release.

**Comment by anandrkris** [comment]
@rainemak Thanks! :clap:

**Comment by rainemak** [comment]
Closing
