### ISSUE TITLE
Ad possibility to add other search engines

### ISSUE THREAD

**Issue by BonoNL** [sailfishos/sailfish-browser#254]
Please add the option to simply add other existing search engines by url.

**Comment by william20111** [comment]
This is quite a key feature i think it should be included with some kind of GUI option to add more. In the mean time at least add some more options in there. duckduckgo is a big one missing.

**Comment by siteshwar** [comment]
I am taking this bug.

**Comment by BonoNL** [comment]
Great.

Beer for you!

Date: Thu, 2 Apr 2015 05:28:31 -0700
