### ISSUE TITLE
Browser can't handle multiple-size favicons

### ISSUE THREAD

**Issue by anandrkris** [sailfishos/sailfish-browser#257]
https://together.jolla.com/question/36161/browser-cant-handle-multiple-size-favicons/ More here. Created here for visibility.

**Comment by rainemak** [comment]
Thanks for pasting this here as well.

This tjc issue has not got much attention as favorite icon size implementation changed along with new browser ui.

I'm well aware of the "broken" icon in m.yle.fi. This is looks to be broken in Qt.

**Comment by anandrkris** [comment]
Glad to know that you're aware of the TJC issue. Oh...ok. 
My intention of posting here is also to bring visibility to any community developers who are interested to fix it.
I suppose, some upstream reports are filed already for Qt ?

**Comment by rainemak** [comment]
Already fixed. Favicon has been fading away for long and we do have support for different link rel types providing high resolution icons.
