### ISSUE TITLE
Bookmark context menu not working correctly

### ISSUE THREAD

**Issue by nodevel** [sailfishos/sailfish-browser#279]
I have experienced this bug in the new browser UI.

It can be reproduces as follows:
1. Click on the URL bar
2. Tap and hold on a bookmark until the context menu appears
3. Raise your finger (keeping the context menu open)
4. Try to select any of the first two items ('Open in tab' or 'Share').

What should happen:
* An item should be selected

What happens instead:
* First two items cannot be selected, unless you select the third one and drag your finger upwards.
* A small drag can close the bookmark view, but the context menu remains open, which results in a shadow over the current website.

**Comment by lewadedun** [comment]
I can not repeat

**Comment by rainemak** [comment]
Closing this one as fixed.
