### ISSUE TITLE
[Feature request] swipe left/right for forward/backward history

### ISSUE THREAD

**Issue by 127001** [sailfishos/sailfish-browser#305]
Would be great if the swipe left/right that's all over in the Sailfish UI was implemented into the browser. At least to go back a page in history. The button at the buttom works, but isn't in line with the rest of the UI.

I understood from Jaakko Roppola (https://twitter.com/JaakkoRoppola/status/573102057005195264) that this is missing for several reasons, one being 'not possible'. For desktop users there are some plugins, like http://www.xuldev.org/firegestures/ that implement a similar feature based on gestures made with the mouse. Sounds like it would be posible to implement it in the sailfish browser too.

**Comment by siteshwar** [comment]
See https://github.com/sailfishos/sailfish-browser/issues/10

**Comment by 127001** [comment]
Ah, my bad. Wasn't searching good enough. Duplicate of #10
