### ISSUE TITLE
[bug] Back button works only once in private mode

### ISSUE THREAD

**Issue by rweickelt** [sailfishos/sailfish-browser#367]
Affects the version bundled with sailfish-os 1.1.6.27

1. Open the browser in private mode
2. Open any web page and browse at least 3 web pages to create a history depth of min 3.
3. Use the back button to go to the previous page

The back button disappears after going back once. However, the browser history is still there.

Work around:
1. Open the tab view down in the left corner
2. Choose the current tab

This re-enables the back button once and has to be repeated each time.

**Comment by rojkov** [comment]
I think this bug isn't reproducible since sailfish-browser 1.3.11 (expected in the next update after 1.1.7).

**Comment by homeworkprod** [comment]
I've experienced exactly what @rweickelt described. Thanks for opening the issue.

**Comment by homeworkprod** [comment]
@rojkov, what behavior will v1.3.11 have?

Also, what is the part that you consider as a bug?

- The back button being available for more than one step back?
- The back button disappearing in the browser bar after a few steps forward?

**Comment by rojkov** [comment]
@homeworkprod The code responsible for maintaining the state of the back/forward buttons has been completely removed from the code base (it used an on-disk  sqlite database to maintain the state hence the correct work in the private mode was impossible). After 1.3.11 the browser relies on the session history maintained by the engine (Gecko). I presume the two bugs you've described should be gone as well.

**Comment by rweickelt** [comment]
I confirm that this bug has been resolved in sailfishos release 1.1.9.28.

**Comment by homeworkprod** [comment]
@rweickelt, so what's the new behaviour then? Back button is only available for one step back, and the workaround doesn't work anymore?

**Comment by rweickelt** [comment]
The one You would expect from a back button in every browser: "Go back one
entry in the history each time You push it and do not suddenly disappear."

**Comment by homeworkprod** [comment]
@rweickelt, thanks for the clarification.

I was worried that the back button would stay/become limited in its classic functionality, given that some desktop browsers limit history in private mode by refusing to re-open (accidentally) closed tabs, for example.
