### ISSUE TITLE
NodeBB Sidebar is unusable

### ISSUE THREAD

**Issue by theblackcrow1** [sailfishos/sailfish-browser#432]
Hello Sailfish Browser developers,

on nodebb forums, the menu sidebar doesn't work at all. For example:
https://community.nodebb.org/

Open this page with the jolla browser. There will be a "hamburger" icon on the top right - when you click it, the navigation sidebar appears for a second and then disappears again instantly.

Sadly that way the navigation can't be used.

Could you fix this please?

Thanks a lot!

**Comment by rainemak** [comment]
Thanks for reporting!

**Comment by siteshwar** [comment]
This bug is always reproducible with current public release of browser, however I am not able to reproduce it with latest changes made for gecko38. It should be closed when we ship gecko38.

**Comment by theblackcrow1** [comment]
Thanks, when do you think it will be released?

**Comment by rainemak** [comment]
Fixed some time ago already.
