### ISSUE TITLE
Transparent dialog backgrounds on twitter.com broken in gecko 38

### ISSUE THREAD

**Issue by rainemak** [sailfishos/sailfish-browser#452]
All the dialog backgrounds in v38 turn white/grey when the page is scrolled a bit down. Works fine in v31, broken in v38.

Steps to reproduce:
1) Login to m.twitter.com
2) Swipe on top of a tweet
3) Select retweet

Expected outcome:
Tweet list renders correctly behind the "Retweet this to you followers?" popup

Actual outcome:
Background behind the "Retweet this to you follows?" popup is greyish and tweer list is not visible.

Note: Works fine with Gecko 31.

**Comment by siteshwar** [comment]
This issue is not always reproducible. However I was able to reproduce it more frequently in landscape mode.

**Comment by rainemak** [comment]
Old, closing.
