### ISSUE TITLE
Browser prints plenty of removeEventListener is not a function

### ISSUE THREAD

**Issue by rainemak** [sailfishos/sailfish-browser#453]
Getting bunch of removeEventListener errors from running JetStream benchmark: http://browserbench.org/JetStream/ with Jolla/Sailfish OS 2.0.0.7

loka 07 11:00:27 Jolla lipstick[961]: * Call to xpconnect wrapped JSObject produced this error:  *
loka 07 11:00:27 Jolla lipstick[961]: [Exception... "[JavaScript Error: "Services.embedlite.chromeEventHandler(...).removeEventListener is not a function" {file: "file:///usr/lib/mozembedlite//components/EmbedLiteErrorPageHandler.js" line: 47}]'[JavaScript Error: "Services.embedlite.chromeEventHandler(...).removeEventListener is not a function" {file: "file:///usr/lib/mozembedlite//components/EmbedLiteErrorPageHandler.js" line: 47}]' when calling method: [nsIDOMEventListener::handleEvent]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: http://browserbench.org/JetStream/JetStreamDriver.js :: runCode :: line 147"  data: yes]

**Comment by siteshwar** [comment]
Not repproducible with gecko 38. I am using below packages on my device :

```
xulrunner-qt5-38.0.5.3+nemo_embedlite_38.20151109122853.9214377-10.71.1.jolla.armv7hl
qtmozembed-qt5-1.13.5-10.40.5.jolla.armv7hl
embedlite-components-qt5-1.9.7-10.24.8.jolla.armv7hl
```

**Comment by rainemak** [comment]
Fixed in https://git.merproject.org/mer-core/embedlite-components/merge_requests/9
