### ISSUE TITLE
[Bug] Segmentation fault on bigger screens (Jolla Tablet)

### ISSUE THREAD

**Issue by Alex217** [sailfishos/sailfish-browser#462]
I am able to (quite often) reproduce a Segmantation fault via the UI.

**How to reproduce:**

1. Open the Sailfish browser on your Jolla Tablet and load any web page. Maybe you should also have some more tabs open (tested with 3 tabs).
2. Now click in the utmost lower left corner (directly on the display-corner next to the tab-icon).
3. It will often trigger the tab-view as expected, but in lot of cases - it happens to me also very often on a daily usage - the browser will crash immediately with a Segmentation fault, if you hit the right spot next to the tab-icon.

I was not able to reproduce this on the Jolla Phone. I think this is because of the little space left for the browser bar on the Phone.

The Terminal output I got is the following:

`[D] DeclarativeCoverActionList::startDbusService:390 - void DeclarativeCoverActionList::startDbusService()
[D] DeclarativeCoverActionList::startDbusService:400 - void DeclarativeCoverActionList::startDbusService() "dbus ready com.jolla.coveraction.pid12960.id1"
[D] DeclarativeCoverActionList::disableActiveCovers:370 - void DeclarativeCoverActionList::disableActiveCovers() "disableActiveCovers, process: /usr/bin/sailfish-browser, winId: 1, action count: 1, enabled: 0"
[D] DeclarativeCoverActionList::setWindowProperty:270 - void DeclarativeCoverActionList::setWindowProperty(QStringList, bool)
[D] DeclarativeCoverActionList::setWindowProperty:280 - void DeclarativeCoverActionList::setWindowProperty(QStringList, bool) "CoverActionList::setWindowProperty: "
[D] DeclarativeCoverActionList::stopDbusService:411 - void DeclarativeCoverActionList::stopDbusService()
Segmentation fault
[nemo@Jolla ~]$`

**Comment by meneer** [comment]
This also happens on 2.0.1.11.

**Comment by Alex217** [comment]
This bug seems to be fixed in latest 2.0.2.51 Aurajoki Sailfish OS release (sailfish-browser-1.13.69.1-10.32.2.jolla.armv7hl).
