### ISSUE TITLE
Site specific: Cookie overlay on Twitter not closeable

### ISSUE THREAD

**Issue by schmittlauch** [sailfishos/sailfish-browser#464]
The EU cookie notification banner on detail pages can't be closed using the close button.

**How to reproduce:**

1. Open Jolla browser in Private mode (so that existing cookies aren't used)
1. Visit a tweet detail page e. g. https://mobile.twitter.com/locusf/status/679731846100328448
1. Click on the *Close* button

**Expected result:** Cookie overlay shall be closed

**Actual result:** Cookie overlay doesn't close

**Comment by rainemak** [comment]
Thanks for reporting. Need to investigate what's going on.

**Comment by schmittlauch** [comment]
Works again, I guess Twitter changed something.

**Comment by rainemak** [comment]
Thanks @schmittlauch for checking this again!
