### ISSUE TITLE
Website shows only a blank page

### ISSUE THREAD

**Issue by gitarra** [sailfishos/sailfish-browser#495]
When trying to view this website one can only see a blank page.

http://www.ruokatieto.fi/ruokakasvatus/ruokaketju-ruuan-matka-pellolta-poytaan/elintarviketeollisuus/elintarvikkeiden-valmistus/maitotuotteet

**Comment by rainemak** [comment]
Thanks for reporting. Could be same error as with www.laitilan.com that also reproduces with Android FF 38.
