### ISSUE TITLE
White cover for the tab view

### ISSUE THREAD

**Issue by fsausset** [sailfishos/sailfish-browser#506]
When displayng the tabs inside the browser and going back to home screen, the cover displayed is the last opened tab. After a while (hard to isolate causes) it becomes white...
On jolla C with sailfish 2.0.2.51

**Comment by fsausset** [comment]
I managed to reproduce it: it happens if I close the last opened tab before going back to home screen.

**Comment by rainemak** [comment]
@fsausset thanks for reporting. Managed to reproduce.

**Comment by rainemak** [comment]
Fix merged and scheduled for 2.0.4. @fsausset again thanks for reporting.

**Comment by fsausset** [comment]
Thanks for the quick fix!
