### ISSUE TITLE
[bug] browser crashes because of missing favicon.ico

### ISSUE THREAD

**Issue by Nokius** [sailfishos/sailfish-browser#548]
On my Jolla1 the browser crashed directly after launching. 

During debugging the issue I saw in the logs this line

~~~~
[W] unknown:34 - file:///usr/share/sailfish-browser/pages/components/FavoriteItem.qml:34:5: QML FavoriteIcon: Error decoding: http://maps.skobbler.de/favicon.ico: Unable to read image data
~~~~

After deleting all my bookmarks the browser worked as normal.

From what I see the browser saves the url of the favicon.ico as reverence for the Bookmark icon. If this reverence is gone the Browser stops working for the user. 

Is there maybe a solution to not let a) keep that happen b) bee the solution/workaround to delete bookmarks 

Thanks in advance

**Comment by rainemak** [comment]
Thanks for the report, will give a look.

**Comment by rainemak** [comment]
Icons are fetched and saved to avoid this kind of errors. I could not reproduce the issues with 2.1.0.x. What is the OS version that you're using?

**Comment by Nokius** [comment]
Happen yesterday with my Jolla1 on latest cbeta RC

**Comment by rainemak** [comment]
Ancient bug and should no longer happen as we icons are saved locally.
