### ISSUE TITLE
Browser http auth empty username not possible

### ISSUE THREAD

**Issue by jsm222** [sailfishos/sailfish-browser#567]
In the browser you cannot do http basic auth with no username set, for instance to vlc http interface and some routers.
[problematic line](https://github.com/sailfishos/sailfish-browser/blob/cc1d81b06c654fbbd6bb3105e2b028a73bc6db59/src/pages/components/AuthDialog.qml#L26)
[Asked here on tjc](https://together.jolla.com/question/163757/browser-http-auth-empty-username/)

**Comment by rainemak** [comment]
Fixed in here:
https://github.com/sailfishos/sailfish-components-webview/pull/33
