### ISSUE TITLE
Content DPI is wrongly calculated after 2.1.3.7 update MER#1855

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [sailfishos/sailfish-browser#580]
On Motorola Moto G2 everything is too small and on Motorola Moto X Play everything is too big. Moto G2 has 5" HD display and X Play has 5.5" FullHD display. More details in [https://bugs.merproject.org/show_bug.cgi?id=1855](mer bug)
![dpml3-6uqaaouex](https://user-images.githubusercontent.com/11545014/33118940-b91282a4-cf6d-11e7-8261-5f94f47f1534.jpg)
![dpml3-ew0aaczkl](https://user-images.githubusercontent.com/11545014/33118941-b9306c4c-cf6d-11e7-802d-6b627c42ebed.jpg)

**Comment by rainemak** [comment]
Does Silica reports correct Theme.pixel ratio?

Could you try to hack a bit some qml file that import Silica by adding (import Sailfish.Silica 1.0):
```
Component.onCompleted: console.log("================= Theme.pixelRatio:", Theme.pixelRatio)
```
Or editing the existing attach Component.onCompleted signal handler.

**Comment by Michal-Szczepaniak** [comment]
@rainemak i can try i know how to make app so that's not problem. I'll post results later today.

**Comment by Michal-Szczepaniak** [comment]
@rainemak Good catch pixelRatio is wrong

> [D] onCompleted:41 - ================= Theme.pixelRatio: 0.949999988079071

while i set in droid-configs-device pixel ratio to 1.0

**Comment by Michal-Szczepaniak** [comment]
ah sorry it's reported correctly on both. I just had it set to 9.5 and didn't noticed :)

**Comment by Michal-Szczepaniak** [comment]
@rainemak what about this? https://github.com/sailfishos/sailfish-browser/commit/13964165e48bba25a9be88b2ae5e8bddad770161#diff-0e59a9dc6f6283976430d17c8f4c41a9L404

**Comment by rainemak** [comment]
By any chance could check this one again. Is this still valid?

**Comment by Michal-Szczepaniak** [comment]
oh my such old issue. This was fixed ages ago.

**Comment by rainemak** [comment]
@Michal-Szczepaniak that's what I thought but I don't have Moto devices.

**Comment by Michal-Szczepaniak** [comment]
@rainemak so i'm confirming then that it's fixed :P
