### ISSUE TITLE
site specific: lupa.cz, enormous memory consumption

### ISSUE THREAD

**Issue by Karry** [sailfishos/sailfish-browser#585]
There was something changed in recent week on lupa.cz (news site). When I am opening it in browser, it fills in device memory to 60% (Intex, 2 GiB of ram) and it is terminted by system then.

**Comment by rainemak** [comment]
Thanks for the report, cloned to internal bugzilla.

**Comment by Karry** [comment]
This problem still exists with browser version in SFOS  3.0.0.5

**Comment by Karry** [comment]
Seems to be fixed after gecko ugrade in latest SFOS (3.0.3.*)
