### ISSUE TITLE
The UA of Google search website is broken

### ISSUE THREAD

**Issue by Alex217** [sailfishos/sailfish-browser#660]
Since a few weeks the Google.com/de etc. website shows the desktop version instead of the mobile website, please fix this. :)

**Comment by rainemak** [comment]
I have reported this already earlier to our bugzilla. Thanks for being active on the matter.

There's a chance, currently feels quite small though, that we can fix this with an user-agent override. I wrote some instructions to the https://sailfishos.org/wiki/Sailfish_OS_Cheat_Sheet#Debugging_User-Agent_problems some time back if you're interested in debugging UA matters.

Easiest is to start browser from command line like:

> CUSTOM_UA="Mozilla/5.0 (Linux; U; Sailfish 3.0; Mobile; rv:45.0) Gecko/45.0 Firefox/45.0 SailfishBrowser/1.0" sailfish-browser www.google.com

Replacing the user-agent with something else of course. We are more than happy to take user-agent override fixes from the community for the Sailfish Browser. Further note, user-agent override deployment is not bound to the Sailfish OS software upgrade cycle.

Thanks again @Alex217 .

**Comment by rainemak** [comment]
This has been fixed more than a year ago. As the fix was a user-agent override fix, the fix has been over-the-air updated for devices that are running esr45 or newer.
https://github.com/sailfishos/sailfish-browser/commit/a7950c57cdbabacdf1108faea81d7227ef17035d
