### ISSUE TITLE
[Bug] Angular.js slider is not working.

### ISSUE THREAD

**Issue by PizzaProgram** [sailfishos/sailfish-browser#930]
Angular.js sliders can not be dragged. It drops to 0, shows NaN.
Test:  https://material.angularjs.org/latest/demo/slider
(Many users reported same problem at Telegram SFOS Fan Club channel.)

It is good possible the problem occurs only based on Node.js version: **16**.

**Comment by PizzaProgram** [comment]
Any update on this?
SFOS v4.3 Browser still not working.

**Comment by rainemak** [comment]
Already fixed. Could not reproduce neither with esr78 nor with esr91. Closing.
